const { cmd } = require('../command');
const axios = require('axios');

cmd({
    pattern: "welcome",
    alias: ["welcomeimg", "welcomeimage", "welimg", "wlc"],
    desc: "Generate stylish welcome image",
    category: "maker",
    react: "👋",
    filename: __filename
}, async (conn, mek, m, { from, sender, reply, pushName }) => {
    try {
        // Get quoted message or user info
        let text = "";
        let quoted = m.quoted ? m.quoted : m;
        let user = m.mentionedJid && m.mentionedJid[0] ? m.mentionedJid[0] : sender;
        let username = pushName || "User";
        
        // Parse parameters
        const args = m.body.slice(m.prefix.length).trim().split(/ +/);
        const command = args.shift().toLowerCase();
        
        // Check if user provided custom parameters
        if (args.length > 0) {
            // Try to parse parameters in format: username|guildname|membercount
            const input = args.join(" ");
            if (input.includes("|")) {
                const params = input.split("|");
                if (params.length >= 3) {
                    username = params[0].trim();
                    const guildName = params[1].trim();
                    const memberCount = params[2].trim();
                    
                    // Generate with custom parameters
                    return await generateWelcome(conn, from, mek, m, reply, username, guildName, memberCount);
                }
            }
        }
        
        // Default welcome for the user
        await generateWelcome(conn, from, mek, m, reply, username, "DARKZONE-MD", "100+");
        
    } catch (error) {
        console.error("Error in welcome command:", error);
        await reply("❌ Error generating welcome image! Please try again.");
        await conn.sendMessage(from, { react: { text: '❌', key: m.key } });
    }
});

async function generateWelcome(conn, from, mek, m, reply, username, guildName, memberCount) {
    try {
        await conn.sendMessage(from, { react: { text: '⏳', key: m.key } });
        
        // Default avatar URL (you can customize this)
        const defaultAvatar = "https://api.deline.web.id/Uy4yBXYUSd.jpg";
        const defaultBackground = "https://api.deline.web.id/Eu3BVf3K4x.jpg";
        
        // Encode parameters
        const encodedUsername = encodeURIComponent(username);
        const encodedGuildName = encodeURIComponent(guildName);
        const encodedAvatar = encodeURIComponent(defaultAvatar);
        const encodedBackground = encodeURIComponent(defaultBackground);
        
        // Build API URL
        const apiUrl = `https://api.deline.web.id/canvas/welcome?username=${encodedUsername}&guildName=${encodedGuildName}&memberCount=${memberCount}&avatar=${encodedAvatar}&background=${encodedBackground}&quality=99`;
        
        // Send processing message
        await reply(`🎨 *Generating Welcome Image...*\n\n• Username: ${username}\n• Group: ${guildName}\n• Members: ${memberCount}\n\nPlease wait...`);
        
        // Call API
        const response = await axios.get(apiUrl, {
            responseType: 'arraybuffer',
            timeout: 30000
        });
        
        if (!response.data || response.data.length === 0) {
            return await reply("❌ Failed to generate image! API returned empty response.");
        }
        
        // Send the generated image
        await conn.sendMessage(from, {
            image: response.data,
            caption: `👋 *Welcome ${username}!*\n\n🏠 Welcome to *${guildName}*\n👥 Total Members: *${memberCount}*\n\nGenerated by DARKZONE-MD`
        }, { quoted: mek });
        
        await conn.sendMessage(from, { react: { text: '✅', key: m.key } });
        
    } catch (error) {
        console.error("Error generating welcome image:", error);
        throw error;
    }
}

// Additional command for custom welcome
cmd({
    pattern: "welcomecustom",
    alias: ["customwelcome", "welcomegen"],
    desc: "Generate custom welcome image with parameters",
    category: "maker",
    react: "🎨",
    filename: __filename
}, async (conn, mek, m, { from, q, reply }) => {
    try {
        if (!q) {
            return await reply(`🎨 *Custom Welcome Generator*\n\nUsage:\n.welcomecustom username|groupname|membercount\n\nExample:\n.welcomecustom Agas|DARKZONE|150\n.welcomecustom John|WhatsApp Group|50`);
        }
        
        const params = q.split("|");
        if (params.length < 3) {
            return await reply("❌ *Invalid Format!*\n\nCorrect format:\nusername|groupname|membercount\n\nExample:\nAgas|DARKZONE-MD|100");
        }
        
        const username = params[0].trim();
        const guildName = params[1].trim();
        const memberCount = params[2].trim();
        
        await generateWelcome(conn, from, mek, m, reply, username, guildName, memberCount);
        
    } catch (error) {
        console.error("Error in welcomecustom command:", error);
        await reply("❌ Error generating custom welcome image!");
        await conn.sendMessage(from, { react: { text: '❌', key: m.key } });
    }
});
